### ISSUE TITLE
Secure Kyma Environment Broker endpoints with Istio Authorization Policy and Authentication Request

### ISSUE THREAD

**Issue by strekm** [kyma-project/control-plane#1540]
**Description**

KEB endpoints are exposed and secured with ORY oathkeeper Rules.  There are 2 types of rules used: jwt (configuration pointing to dex) and oauth2 introspection with ORY Hydra. Since kyma 2 is not supporting dex anymore and api-gateway moving into direction to utilise Istio more security concept for KEB needs to be reworked. 

AC:
- [x] POC switching ORY Hydra to issue jwt instead of opaque oauth2 tokens
- [x] security validation for switching hydra to issue jwt
- [x] POC with httpbin exposing endpoint with apirules and and Istio CR
- [x] ORY hydra configured to issue jwt, self issuer configured -> in progress by @strekm 
- [x] [KEB endpoints exposed and secured with Istio CR](https://github.com/kyma-project/control-plane/issues/1732)
- [x] [ORY oathkeeper deleted from KCP](https://github.com/kyma-project/control-plane/issues/1804)
- [x] necessary documentation updated

**Reasons**

Dropping dependency to ORY. Simplify architecture of KCP itself and dependencies.

**Attachments**

https://github.com/kyma-project/control-plane/pull/487/files
https://github.com/kyma-project/control-plane/blob/main/resources/kcp/charts/kyma-environment-broker/templates/oathkeeper-rule.yaml
https://kyma-project.io/docs/kyma/main/03-tutorials/00-api-exposure/apix-04-expose-and-secure-workload-istio/
https://github.com/kyma-project/kyma/issues/12669
