### ISSUE TITLE
Make promtool for Alert tests part of KMC build pipeline 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/control-plane#826]
**Description**

Prometheus alerts for Kyma Metrics Collector are tested using [promtool](https://github.com/prometheus/prometheus/tree/main/cmd/promtool). But this is only done manually in a dev set up. The goal here is to enrich the Prow job for KMC to test the alerts with promtool as well.  

**Reasons**

Automation

**Tasks**
- [ ] find out what are the manual tests  
- [ ] add unit tests for the alerts to automate those manual tests
- [ ] add a prowjob for every pr to execute those tests

**Comment by VladislavPaskar** [comment]
Question:
- we want to automate this process, but are they already manual steps of how to test it ?
